skins.2=2
name.2=iregex:(PinkSheep|Pink Sheep)

skins.3=3
name.3=iregex:(PurpleShep|Purple Shep)

skins.4=4
name.4=iregex:(PinkGlasses|Pink Glasses|Pink Sheep with Glasses)

skins.5=5
name.5=iregex:(PinkDerp|Pink Derp|Derpy Pink Sheep)

skins.6=6
name.6=iregex:(PinkBigEyes|Pink Big Eyes|Pink Sheep with Big Eyes)

skins.7=7
name.7=iregex:(PurpleMonocle|Purple Monocle|Purple Shep with Monocle)

skins.8=8
name.8=iregex:(PurpleGlasses|Purple Glasses|Purple Shep with Glasses)

skins.9=9
name.9=iregex:(CrystalSheep|Crystal Sheep)

skins.10=10
name.10=iregex:(ShadowSheep|Shadow Sheep)